- hosts: localhost
  connection: local
  become: no
  roles:
    - { role: kubernetes_off, when: baremetal | default(True) | bool }
    - { role: kubernetes_on, when: not baremetal | default(False) | bool }
